locations:
  # The place to look for files to be scanned
  staging: /path/to/staging/area
  # The place to put results
  completed: /path/to/completed/results/area
email_smtp:
  address: smtp.google.com
  port: 587
  domain: mail.gmail.com
  user_name: mr_test@gmail.com
  password: password
  to: mr_test@gmail.com
  subject: OFAC Task Complete
file:
  csv:
    name_header: Name
    name_structure: last_first
  ach:
    name_header: 
    name_structure: first_last