locations:
  staging: /path/to/staging/area
  completed: /path/to/completed/results/area
email_smtp:
  address: smtp.google.com
  port: 587
  domain: mail.gmail.com
  user_name: mr_test@gmail.com
  password: password
  to: mr_test@gmail.com
  subject: OFAC Task Complete